//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertaProgramacion
    {
        public int AlertaProgramacionId { get; set; }
        public int AlertaId { get; set; }
        public int FrecuenciaEnvio { get; set; }
        public int NroDias { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public int HoraEnvio { get; set; }
        public Nullable<System.DateTime> FechaUltimoEnvio { get; set; }
        public string Buzones { get; set; }
        public int ComponenteImpactado { get; set; }
        public bool FlagActivo { get; set; }
        public string Asunto { get; set; }
    
        public virtual Alerta Alerta { get; set; }
    }
}
