//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alerta()
        {
            this.AlertaProgramacion = new HashSet<AlertaProgramacion>();
            this.AlertaDetalle = new HashSet<AlertaDetalle>();
        }
    
        public int AlertaId { get; set; }
        public int TipoAlertaId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool FlagActivo { get; set; }
        public Nullable<System.DateTime> FechaUltimaEjecucion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertaProgramacion> AlertaProgramacion { get; set; }
        public virtual TipoAlerta TipoAlerta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertaDetalle> AlertaDetalle { get; set; }
    }
}
