//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertaDetalle
    {
        public int AlertaDetalleId { get; set; }
        public int AlertaId { get; set; }
        public string Descripcion { get; set; }
        public string Detalle { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<bool> FlagActivo { get; set; }
        public Nullable<int> Criticidad { get; set; }
    
        public virtual Alerta Alerta { get; set; }
    }
}
