//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AplicacionCargaMasiva
    {
        public string CodigoAPT { get; set; }
        public string Nombre { get; set; }
        public string DescripcionAplicacion { get; set; }
        public string TipoActivoInformacion { get; set; }
        public string EstadoAplicacion { get; set; }
        public string MotivoCreacion { get; set; }
        public Nullable<System.DateTime> FechaSolicitud { get; set; }
        public string PersonaSolicitud { get; set; }
        public string CategoriaTecnologica { get; set; }
        public string ModeloEntrega { get; set; }
        public Nullable<System.DateTime> FechaCreacionAplicacion { get; set; }
        public string CodigoInterfaz { get; set; }
        public string GerenciaCentral { get; set; }
        public string Division { get; set; }
        public string Area { get; set; }
        public string Unidad { get; set; }
        public string AreaBIAN { get; set; }
        public string DominioBIAN { get; set; }
        public string PlataformaBCP { get; set; }
        public string JefaturaATI { get; set; }
        public string ArquitectoTI { get; set; }
        public string GestionadoPor { get; set; }
        public string Owner_LiderUsuario_ProductOwner { get; set; }
        public string Gestor_UsuarioAutorizador_ProductOwner { get; set; }
        public string Experto_Especialista { get; set; }
        public string JefeEquipo_ExpertoAplicacionUserIT_ProductOwner { get; set; }
        public string BrokerSistemas { get; set; }
        public string TribeTechnicalLead { get; set; }
        public string GestorUserIT { get; set; }
        public string NombreEquipo_Squad { get; set; }
        public string EntidadResponsable { get; set; }
        public string EntidadUso { get; set; }
        public string TipoDesarrollo { get; set; }
        public string Proveedor { get; set; }
        public string Ubicacion { get; set; }
        public string Infraestructura { get; set; }
        public string Contingencia { get; set; }
        public string MetodoAutenticacion { get; set; }
        public string MetodoAutorizacion { get; set; }
        public string AmbienteInstalacion { get; set; }
        public string FlagOOR { get; set; }
        public string FlagRatificaOOR { get; set; }
        public string AplicacionReemplazo { get; set; }
        public string ClasificacionTecnica { get; set; }
        public string SubclasificacionTecnica { get; set; }
        public string RutaRepositorio { get; set; }
        public string GrupoTicketRemedy { get; set; }
        public string InterfazApp { get; set; }
        public string CompatibilidadWindows { get; set; }
        public string CompatibilidadNavegador { get; set; }
        public string ProcesoClave { get; set; }
        public string SWBase_SO { get; set; }
        public string SWBase_HP { get; set; }
        public string SWBase_LP { get; set; }
        public string SWBase_BD { get; set; }
        public string SWBase_Framework { get; set; }
        public string RET { get; set; }
        public string GestorAplicacionCTR { get; set; }
        public string ConsultorCTR { get; set; }
        public string InstaladaDesarrollo { get; set; }
        public string InstaladaCertificacion { get; set; }
        public string InstaladaProduccion { get; set; }
        public string CriticidadAplicacionBIA { get; set; }
        public string ProductoMasRepresentativo { get; set; }
        public string MenorRTO { get; set; }
        public string MayorGradoInterrupcion { get; set; }
        public string CriticidadId { get; set; }
        public string RoadmapPlanificado { get; set; }
        public string DetalleEstrategia { get; set; }
        public string EstadoRoadmap { get; set; }
        public string EtapaAtencion { get; set; }
        public string RoadmapEjecutado { get; set; }
        public string FechaInicioRoadmap { get; set; }
        public string FechaFinRoadmap { get; set; }
        public string CodigoAppReemplazo { get; set; }
        public Nullable<int> FilaExcel { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<bool> FlagRegistroValido { get; set; }
    }
}
