//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AplicacionPortafolioResponsables
    {
        public int AplicacionPortafolioResponsableId { get; set; }
        public string CodigoAPT { get; set; }
        public string Matricula { get; set; }
        public string Colaborador { get; set; }
        public bool FlagActivo { get; set; }
        public int PortafolioResponsableId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string ModificadoPor { get; set; }
        public string CorreoElectronico { get; set; }
        public Nullable<bool> FlagSolicitud { get; set; }
        public Nullable<bool> FlagCreado { get; set; }
    
        public virtual PortafolioResponsables PortafolioResponsables { get; set; }
    }
}
