//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationFile
    {
        public int IdApplicationFile { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public byte[] ArchivoAsociado { get; set; }
        public string Comentario { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> FileType { get; set; }
        public Nullable<int> SolicitudId { get; set; }
    }
}
