//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationCargaMasiva
    {
        public int ApplicationCargaMasivaId { get; set; }
        public string applicationId { get; set; }
        public string applicationName { get; set; }
        public string description { get; set; }
        public Nullable<int> implementationType { get; set; }
        public Nullable<int> managed { get; set; }
        public Nullable<int> deploymentType { get; set; }
        public string parentAPTCode { get; set; }
        public Nullable<int> status { get; set; }
        public string interfaceId { get; set; }
        public Nullable<System.DateTime> registerDate { get; set; }
        public Nullable<int> unit { get; set; }
        public string teamName { get; set; }
        public string userEntity { get; set; }
        public string developmentType { get; set; }
        public string developmentProvider { get; set; }
        public Nullable<int> infrastructure { get; set; }
        public string replacementApplication { get; set; }
        public Nullable<int> assetType { get; set; }
        public Nullable<int> BIANdomain { get; set; }
        public Nullable<int> mainOffice { get; set; }
        public Nullable<int> technologyCategory { get; set; }
        public Nullable<int> technicalSubclassification { get; set; }
        public Nullable<int> technicalClassification { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<int> groupTicketRemedy { get; set; }
        public string webDomain { get; set; }
        public Nullable<System.DateTime> dateFirstRelease { get; set; }
        public string starProduct { get; set; }
        public string shorterApplicationResponseTime { get; set; }
        public string highestDegreeInterruption { get; set; }
        public Nullable<int> tobe { get; set; }
        public string tierPreProduction { get; set; }
        public string tierProduction { get; set; }
        public Nullable<int> authorizationMethod { get; set; }
        public Nullable<int> authenticationMethod { get; set; }
        public Nullable<int> architectId { get; set; }
        public Nullable<int> FilaExcel { get; set; }
        public Nullable<bool> FlagRegistroValido { get; set; }
        public Nullable<int> classification { get; set; }
        public Nullable<int> applicationCriticalityBIA { get; set; }
        public Nullable<int> finalCriticality { get; set; }
        public string complianceLevel { get; set; }
        public string summaryStandard { get; set; }
        public Nullable<int> areaBIAN { get; set; }
        public string Experto { get; set; }
        public string ArquitectoNegocio { get; set; }
        public string ArquitectoNegocioMatricula { get; set; }
        public string ArquitectoNegocioEmail { get; set; }
        public string UsuarioAutorizador { get; set; }
        public string BrokerSistemas { get; set; }
        public string BrokerSistemasMatricula { get; set; }
        public string BrokerSistemasEmail { get; set; }
        public string TribeLead { get; set; }
        public string TribeLeadMatricula { get; set; }
        public string TribeLeadEmail { get; set; }
        public string TribeTechnicalLead { get; set; }
        public string TribeTechnicalLeadMatricula { get; set; }
        public string TribeTechnicalLeadEmail { get; set; }
        public string JefeEquipo { get; set; }
        public string JefeEquipoMatricula { get; set; }
        public string JefeEquipoEmail { get; set; }
        public string LiderUsuario { get; set; }
        public string LiderUsuarioMatricula { get; set; }
        public string LiderUsuarioEmail { get; set; }
        public Nullable<bool> FlagRegistroDistinto { get; set; }
        public string FlagPirata { get; set; }
        public Nullable<int> Division { get; set; }
        public Nullable<int> Gerencia { get; set; }
        public string tipoPCI { get; set; }
    }
}
