//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationFlow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationFlow()
        {
            this.ApplicationFlowData = new HashSet<ApplicationFlowData>();
        }
    
        public int FlowAppId { get; set; }
        public int AppId { get; set; }
        public Nullable<int> typeRegister { get; set; }
        public Nullable<int> typeFlow { get; set; }
        public string ownerId { get; set; }
        public string ownerEmail { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> dateCreation { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> dateApproved { get; set; }
        public string approvedBy { get; set; }
        public Nullable<System.DateTime> dateRejected { get; set; }
        public string rejectedBy { get; set; }
        public Nullable<System.DateTime> dateTransfer { get; set; }
        public string transferedBy { get; set; }
        public Nullable<bool> isCompleted { get; set; }
        public Nullable<bool> isNotified { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> lastFlowAppId { get; set; }
        public Nullable<int> SolicitudAplicacionId { get; set; }
        public string approvedByName { get; set; }
        public string rejectedByName { get; set; }
        public string transferedByName { get; set; }
        public Nullable<bool> isActiveOwner { get; set; }
        public string RegistradoPor { get; set; }
        public string observedBy { get; set; }
        public Nullable<System.DateTime> dateObserved { get; set; }
        public string observedByName { get; set; }
        public Nullable<bool> isObserved { get; set; }
    
        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationFlowData> ApplicationFlowData { get; set; }
    }
}
