//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationFlowData
    {
        public int DataId { get; set; }
        public int FlowAppId { get; set; }
        public Nullable<int> fieldId { get; set; }
        public string currentValue { get; set; }
        public string newValue { get; set; }
        public Nullable<System.DateTime> dateCreation { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> dateModification { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<int> typeFlow { get; set; }
    
        public virtual ApplicationFlow ApplicationFlow { get; set; }
    }
}
