//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationManagerCatalog
    {
        public int applicationManagerCatalogId { get; set; }
        public string applicationId { get; set; }
        public string username { get; set; }
        public string managerName { get; set; }
        public bool isActive { get; set; }
        public int applicationManagerId { get; set; }
        public System.DateTime dateCreation { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> dateModification { get; set; }
        public string modifiedBy { get; set; }
        public string email { get; set; }
    
        public virtual ApplicationManager ApplicationManager { get; set; }
    }
}
