//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationHistorico
    {
        public int AppId { get; set; }
        public string applicationId { get; set; }
        public string applicationName { get; set; }
        public string description { get; set; }
        public string interfaceId { get; set; }
        public string parentAPTCode { get; set; }
        public string gerencia { get; set; }
        public string division { get; set; }
        public string area { get; set; }
        public string unity { get; set; }
        public string managed { get; set; }
        public string implementationType { get; set; }
        public string deploymentType { get; set; }
        public string status { get; set; }
        public string teamName { get; set; }
        public string userEntity { get; set; }
        public string developmentType { get; set; }
        public string developmentProvider { get; set; }
        public string replacementApplication { get; set; }
        public string infrastructure { get; set; }
        public string authenticationMethod { get; set; }
        public string authorizationMethod { get; set; }
        public string groupTicketRemedy { get; set; }
        public string webDomain { get; set; }
        public Nullable<decimal> complianceLevel { get; set; }
        public string summaryStandard { get; set; }
        public string assetType { get; set; }
        public string BIANArea { get; set; }
        public string BIANdomain { get; set; }
        public string mainOffice { get; set; }
        public string tobe { get; set; }
        public string technologyCategory { get; set; }
        public string technicalSubclassification { get; set; }
        public string technicalClassification { get; set; }
        public string tierProduction { get; set; }
        public string tierPreProduction { get; set; }
        public string applicationCriticalityBIA { get; set; }
        public string classification { get; set; }
        public string finalCriticality { get; set; }
        public string starProduct { get; set; }
        public string shorterApplicationResponseTime { get; set; }
        public string highestDegreeInterruption { get; set; }
        public Nullable<System.DateTime> dateFirstRelease { get; set; }
        public Nullable<int> tribeTechnicalLeadId { get; set; }
        public string tribeTechnicalLeadNombre { get; set; }
        public string tribeTechnicalLeadEmail { get; set; }
        public Nullable<int> jefeDeEquipoId { get; set; }
        public string jefeDeEquipoNombre { get; set; }
        public string jefeDeEquipoEmail { get; set; }
        public Nullable<int> brokerId { get; set; }
        public string brokerNombre { get; set; }
        public string brokerEmail { get; set; }
        public Nullable<int> ownerId { get; set; }
        public string ownerNombre { get; set; }
        public string ownerEmail { get; set; }
        public Nullable<int> gestorId { get; set; }
        public string gestorNombre { get; set; }
        public string gestorEmail { get; set; }
        public Nullable<int> expertoId { get; set; }
        public string expertoNombre { get; set; }
        public string expertoEmail { get; set; }
        public Nullable<int> tribeLeadId { get; set; }
        public string tribeLeadNombre { get; set; }
        public string tribeLeadEmail { get; set; }
        public Nullable<int> solicitanteId { get; set; }
        public string solicitanteNombre { get; set; }
        public string solicitanteEmail { get; set; }
        public Nullable<int> arquitectoEvaluadorId { get; set; }
        public string arquitectoEvaluadorNombre { get; set; }
        public string arquitectoEvaluadorEmail { get; set; }
        public Nullable<int> FilaExcel { get; set; }
        public Nullable<bool> FlagRegistroValido { get; set; }
    }
}
