//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivosCVT
    {
        public int ArchivoId { get; set; }
        public int TablaProcedenciaId { get; set; }
        public string EntidadId { get; set; }
        public string Nombre { get; set; }
        public byte[] Contenido { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string NombreRef { get; set; }
        public string DescripcionRef { get; set; }
    
        public virtual TablaProcedencia TablaProcedencia { get; set; }
    }
}
