//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArquitectoTI
    {
        public int ArquitectoTIId { get; set; }
        public int JefaturaAtiId { get; set; }
        public string Matricula { get; set; }
        public string Correo { get; set; }
        public string Nombre { get; set; }
        public bool FlagActivo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> FlagValidarMatricula { get; set; }
        public Nullable<bool> FlagEliminado { get; set; }
        public Nullable<bool> FlagEncargadoJefatura { get; set; }
    
        public virtual JefaturaAti JefaturaAti { get; set; }
    }
}
