//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseUsuarios
    {
        public int IdUsuario { get; set; }
        public string Matricula { get; set; }
        public string Nombres { get; set; }
        public Nullable<bool> FlagActivo { get; set; }
        public string CorreoElectronico { get; set; }
    }
}
