//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCP_CATG_GH_UNIDADES
    {
        public int BCP_CATG_GH_UNIDADES_ID { get; set; }
        public string COD_UNIDAD { get; set; }
        public string FEC_INICIO_VIGENCIA { get; set; }
        public string FEC_FIN_VIGENCIA { get; set; }
        public string DES_UNIDAD { get; set; }
        public string COD_UNIDAD_SUPERIOR { get; set; }
        public string COD_POSICION_RESPONSABLE { get; set; }
        public string COD_PERSONAL_RESPONSABLE { get; set; }
        public string COD_MATRICULA_RESPONSABLE { get; set; }
        public string COD_JERARQUIA_UNIDAD { get; set; }
        public string COD_SOCIEDAD { get; set; }
        public string NUM_CENTRO_COSTO { get; set; }
        public string COD_SUCURSAL { get; set; }
        public string COD_DEPARTAMENTO { get; set; }
        public string COD_UBICACION_FISICA { get; set; }
        public string COD_DIVISION { get; set; }
        public string COD_AREA { get; set; }
        public string COD_SERVICIO { get; set; }
        public string BLANCO { get; set; }
        public string FEC_ULTIMA_ACTUALIZACION { get; set; }
        public string FEC_PROCESO { get; set; }
    }
}
