//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraAcciones
    {
        public int BitacoraId { get; set; }
        public string CodigoAPT { get; set; }
        public string DetalleBitacora { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string NombreUsuarioCreacion { get; set; }
        public byte[] Archivo { get; set; }
        public string NombreArchivo { get; set; }
    }
}
