//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker
    {
        public int BrokerId { get; set; }
        public int UnidadId { get; set; }
        public string ownerId { get; set; }
        public string ownerName { get; set; }
        public string ownerEmail { get; set; }
        public bool isActive { get; set; }
        public System.DateTime dateCreation { get; set; }
        public Nullable<System.DateTime> dateModification { get; set; }
    
        public virtual Unidad Unidad { get; set; }
    }
}
