//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChapterFuncionesRoles
    {
        public int FuncionProductoId { get; set; }
        public Nullable<int> RolesProductoId { get; set; }
        public string ChapterFuncion { get; set; }
        public Nullable<bool> FlagActivo { get; set; }
        public Nullable<bool> FlagEliminado { get; set; }
        public string Chapter { get; set; }
        public string Funcion { get; set; }
        public string Tribu { get; set; }
        public string RolSeguridad { get; set; }
    }
}
