//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigoCIS_ServidorNoRegistrado
    {
        public int CodigoServidorId { get; set; }
        public int CodigoId { get; set; }
        public string Servidor { get; set; }
    
        public virtual CodigoCIS CodigoCIS { get; set; }
    }
}
