//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigoReservado
    {
        public int CodigoReservadoId { get; set; }
        public Nullable<int> TipoCodigo { get; set; }
        public string Codigo { get; set; }
        public string Comentarios { get; set; }
        public Nullable<bool> FlagActivo { get; set; }
        public Nullable<bool> FlagEliminado { get; set; }
    }
}
