//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultas
    {
        public int ConsultaId { get; set; }
        public Nullable<System.DateTime> FechaConsulta { get; set; }
        public Nullable<int> TipoConsulta { get; set; }
        public string Consulta { get; set; }
        public Nullable<System.DateTime> FechaRespuesta { get; set; }
        public string RespuestaPortafolio { get; set; }
        public string NombreUsuarioConsultor { get; set; }
        public string MatriculaUsuarioConsultor { get; set; }
        public string EmailUsuarioConsultor { get; set; }
        public Nullable<int> Respondido { get; set; }
        public string applicationId { get; set; }
        public Nullable<bool> FlagEliminado { get; set; }
    }
}
