//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuestionarioAplicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuestionarioAplicacion()
        {
            this.CuestionarioAplicacionDetalle = new HashSet<CuestionarioAplicacionDetalle>();
        }
    
        public int CuestionarioAplicacionId { get; set; }
        public string CodigoAPT { get; set; }
        public string GestorAplicacion { get; set; }
        public string Consultor { get; set; }
        public Nullable<decimal> ConfidencialidadCalculo { get; set; }
        public string ConfidencialidadDescripcion { get; set; }
        public Nullable<decimal> IntegridadCalculo { get; set; }
        public string IntegridadDescripcion { get; set; }
        public Nullable<decimal> DisponibilidadCalculo { get; set; }
        public string DisponibilidadDescripcion { get; set; }
        public Nullable<decimal> PrivacidadCalculo { get; set; }
        public string PrivacidadDescripcion { get; set; }
        public string Clasificacion { get; set; }
        public bool FlagActivo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> NivelCriticidad { get; set; }
        public string CriticidadFinal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuestionarioAplicacionDetalle> CuestionarioAplicacionDetalle { get; set; }
    }
}
