//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuestionarioAplicacionDetalle
    {
        public int CuestionarioAplicacionDetalleId { get; set; }
        public int CuestionarioAplicacionId { get; set; }
        public int PreguntaId { get; set; }
        public Nullable<int> AlternativaSeleccionada { get; set; }
        public bool FlagActivo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual CuestionarioAplicacion CuestionarioAplicacion { get; set; }
        public virtual PreguntaPae PreguntaPae { get; set; }
    }
}
