//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.EquipoTecnologia = new HashSet<EquipoTecnologia>();
            this.Relacion = new HashSet<Relacion>();
            this.EquipoConfiguracion = new HashSet<EquipoConfiguracion>();
            this.EquipoCicloVida = new HashSet<EquipoCicloVida>();
        }
    
        public int EquipoId { get; set; }
        public string ProcedenciaId { get; set; }
        public Nullable<int> TablaProcedenciaId { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> TipoEquipoId { get; set; }
        public Nullable<bool> FlagTemporal { get; set; }
        public bool FlagActivo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string ModificadoPor { get; set; }
        public string FechaUltimoEscaneoCorrecto { get; set; }
        public string FechaUltimoEscaneoError { get; set; }
        public Nullable<int> AmbienteId { get; set; }
        public Nullable<bool> FlagExcluirCalculo { get; set; }
        public Nullable<int> DominioServidorId { get; set; }
        public Nullable<int> CaracteristicaEquipo { get; set; }
        public Nullable<System.DateTime> FechaCambioEstado { get; set; }
        public string UsuarioCambioEstado { get; set; }
        public Nullable<bool> FlagCambioDominioRed { get; set; }
        public Nullable<System.DateTime> FechaCambioDominioRed { get; set; }
        public string UsuarioCambioDominioRed { get; set; }
        public Nullable<int> RolServidorId { get; set; }
        public string ComentarioEstado { get; set; }
        public Nullable<bool> FlagCambioEstadoTemporal { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<bool> FlagServidorServicio { get; set; }
        public string Suscripcion { get; set; }
        public string GrupoRecursos { get; set; }
        public Nullable<int> idmodelohardware { get; set; }
        public Nullable<System.DateTime> FechaFinSoporte { get; set; }
    
        public virtual TablaProcedencia TablaProcedencia { get; set; }
        public virtual TipoEquipo TipoEquipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipoTecnologia> EquipoTecnologia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Relacion> Relacion { get; set; }
        public virtual Ambiente Ambiente { get; set; }
        public virtual DominioServidor DominioServidor { get; set; }
        public virtual RolServidor RolServidor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipoConfiguracion> EquipoConfiguracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipoCicloVida> EquipoCicloVida { get; set; }
    }
}
