//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipoSoftwareBase
    {
        public int EquipoSoftwareBaseId { get; set; }
        public int EquipoId { get; set; }
        public int SubdominioId { get; set; }
        public string SoftwareBase { get; set; }
        public Nullable<System.DateTime> FechaLanzamiento { get; set; }
        public Nullable<System.DateTime> FechaFinSoporte { get; set; }
        public Nullable<System.DateTime> FechaFinExtendida { get; set; }
        public Nullable<System.DateTime> FechaFinInterna { get; set; }
        public string ComentariosFechaFin { get; set; }
        public Nullable<int> FechaCalculoId { get; set; }
        public bool FlagActivo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> TipoActivo { get; set; }
        public string Serial { get; set; }
        public string Modelo { get; set; }
        public string Vendor { get; set; }
        public string Tecnologia { get; set; }
        public string Version { get; set; }
        public string Hostname { get; set; }
        public string IP { get; set; }
        public Nullable<int> Dimension { get; set; }
        public string ArquitectoSeguridad { get; set; }
        public string SoportePrimerNivel { get; set; }
        public string Proveedor { get; set; }
        public Nullable<System.DateTime> FechaAdquisicion { get; set; }
        public Nullable<System.DateTime> FechaImplementacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaRenovacion { get; set; }
        public Nullable<System.DateTime> VencimientoLicencia { get; set; }
        public string CantidadLicencia { get; set; }
        public string FormaLicenciamiento { get; set; }
        public string CodigoInventario { get; set; }
        public string CyberSOC { get; set; }
        public Nullable<int> Sede { get; set; }
        public string Sala { get; set; }
        public string RACK { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> Backup { get; set; }
        public Nullable<int> BackupFrecuencia { get; set; }
        public string BackupDescripcion { get; set; }
        public Nullable<int> IntegracionGestorInteligencia { get; set; }
        public string ConectorSIEM { get; set; }
        public Nullable<int> CONA { get; set; }
        public string UmbralCPU { get; set; }
        public string UmbralMemoria { get; set; }
        public string UmbralDisco { get; set; }
        public string UrlNube { get; set; }
        public Nullable<int> Criticidad { get; set; }
        public string EquipoDetalle { get; set; }
        public string EstadoIntegracionSIEM { get; set; }
        public string CONAAvanzado { get; set; }
        public string EstadoAppliance { get; set; }
        public string Ventana { get; set; }
    }
}
