//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipoCicloVida
    {
        public int EquipoCicloVidaId { get; set; }
        public int EquipoId { get; set; }
        public Nullable<System.DateTime> FechaObsolescencia { get; set; }
        public Nullable<System.DateTime> FechaCalculoBase { get; set; }
        public bool EsIndefinida { get; set; }
        public int DiaRegistro { get; set; }
        public int MesRegistro { get; set; }
        public int AnioRegistro { get; set; }
        public int Obsoleto { get; set; }
        public bool FlagActivo { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Equipo Equipo { get; set; }
    }
}
