//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excepcion
    {
        public int ExcepcionId { get; set; }
        public int TipoExcepcionId { get; set; }
        public string CodigoAPT { get; set; }
        public Nullable<int> TipoRiesgoId { get; set; }
        public Nullable<System.DateTime> FechaFinExcepcion { get; set; }
        public string UrlInformacion { get; set; }
        public string Comentario { get; set; }
        public bool FlagActivo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public int TecnologiaId { get; set; }
    
        public virtual Tecnologia Tecnologia { get; set; }
    }
}
