//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestionadoPor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GestionadoPor()
        {
            this.TeamSquad = new HashSet<TeamSquad>();
        }
    
        public int GestionadoPorId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> FlagEquipoAgil { get; set; }
        public bool FlagActivo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> FlagEliminado { get; set; }
        public Nullable<bool> FlagSubsidiarias { get; set; }
        public Nullable<bool> FlagUserIT { get; set; }
        public string CodigoSIGA { get; set; }
        public Nullable<bool> Visualizar { get; set; }
        public Nullable<bool> FlagJefeEquipo { get; set; }
        public Nullable<System.DateTime> Fec_Fin_Vigencia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamSquad> TeamSquad { get; set; }
    }
}
