//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guardicore
    {
        public int id { get; set; }
        public string idguardicore { get; set; }
        public string nombre { get; set; }
        public string nombrecvt { get; set; }
        public string so { get; set; }
        public string fechaescaneo { get; set; }
        public string ip { get; set; }
        public string etiqueta { get; set; }
        public Nullable<int> equipoid { get; set; }
        public Nullable<int> idestado { get; set; }
        public Nullable<System.DateTime> fechaactualizacion { get; set; }
    }
}
