//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardicoreLabels
    {
        public int GuardicoreLabelsId { get; set; }
        public string LabelId { get; set; }
        public string Nombrelabel { get; set; }
        public string CodigoAPT { get; set; }
    }
}
