//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardicoreAssets
    {
        public int GuardicoreAssetsId { get; set; }
        public string id { get; set; }
        public string Name { get; set; }
        public string IPAddresses { get; set; }
        public string Labels { get; set; }
        public string OS { get; set; }
        public string FirstSeen { get; set; }
        public string LastSeen { get; set; }
        public string Status { get; set; }
        public string hostname { get; set; }
        public Nullable<int> EquipoId { get; set; }
    }
}
