//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InitialApplication
    {
        public int InitialApplicationId { get; set; }
        public int AppId { get; set; }
        public string applicationId { get; set; }
        public string applicationName { get; set; }
        public string description { get; set; }
        public Nullable<int> implementationType { get; set; }
        public Nullable<int> managed { get; set; }
        public Nullable<int> deploymentType { get; set; }
        public string parentAPTCode { get; set; }
        public Nullable<int> status { get; set; }
        public string interfaceId { get; set; }
        public Nullable<System.DateTime> registerDate { get; set; }
        public string registerBy { get; set; }
        public Nullable<int> unit { get; set; }
        public string teamName { get; set; }
        public string userEntity { get; set; }
        public string developmentType { get; set; }
        public string developmentProvider { get; set; }
        public Nullable<int> infrastructure { get; set; }
        public string replacementApplication { get; set; }
        public Nullable<int> assetType { get; set; }
        public Nullable<int> BIANdomain { get; set; }
        public Nullable<int> mainOffice { get; set; }
        public Nullable<int> technologyCategory { get; set; }
        public Nullable<int> technicalSubclassification { get; set; }
        public Nullable<int> technicalClassification { get; set; }
        public Nullable<int> area { get; set; }
        public Nullable<int> groupTicketRemedy { get; set; }
        public string webDomain { get; set; }
        public Nullable<System.DateTime> dateFirstRelease { get; set; }
        public string starProduct { get; set; }
        public string shorterApplicationResponseTime { get; set; }
        public string highestDegreeInterruption { get; set; }
        public Nullable<int> applicationCriticalityBIA { get; set; }
        public Nullable<int> classification { get; set; }
        public Nullable<int> finalCriticality { get; set; }
        public Nullable<int> tobe { get; set; }
        public string tierPreProduction { get; set; }
        public string tierProduction { get; set; }
        public Nullable<int> registrationSituation { get; set; }
        public Nullable<bool> isFormalApplication { get; set; }
        public Nullable<System.DateTime> regularizationDate { get; set; }
        public Nullable<int> authorizationMethod { get; set; }
        public Nullable<int> authenticationMethod { get; set; }
        public Nullable<bool> hasInterfaceId { get; set; }
        public Nullable<int> architectId { get; set; }
        public Nullable<int> teamId { get; set; }
        public Nullable<bool> isApproved { get; set; }
        public string approvedBy { get; set; }
        public string approvedByEmail { get; set; }
        public Nullable<System.DateTime> dateApproved { get; set; }
        public Nullable<bool> isImported { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string desactivatedBy { get; set; }
        public string desactivatedByEmail { get; set; }
        public Nullable<System.DateTime> dateDesactivated { get; set; }
        public Nullable<int> deploymentTypeOriginal { get; set; }
        public Nullable<bool> isObserved { get; set; }
        public string commentsObserved { get; set; }
        public string summaryStandard { get; set; }
        public Nullable<decimal> complianceLevel { get; set; }
        public Nullable<System.DateTime> FreezeDate { get; set; }
        public Nullable<bool> isOriginal { get; set; }
        public Nullable<System.DateTime> dateRegistrationSituationComplete { get; set; }
        public Nullable<bool> aplicacionRevertida { get; set; }
        public Nullable<System.DateTime> FechaEliminacion { get; set; }
        public string UsuarioEliminacion { get; set; }
        public Nullable<bool> isReactivated { get; set; }
        public Nullable<System.DateTime> FechaReactivacion { get; set; }
        public Nullable<int> EstadoReactivacion { get; set; }
    }
}
