//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensaje
    {
        public int MensajeId { get; set; }
        public string Asunto { get; set; }
        public string Descripcion { get; set; }
        public int TipoMensajeId { get; set; }
        public Nullable<System.DateTime> FechaUltimaVisita { get; set; }
        public string UsuarioUltimaVisita { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public string NombreUsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual TipoMensaje TipoMensaje { get; set; }
    }
}
