//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificacionResponsableAplicacion
    {
        public int NotificacionResponsableAplicacionId { get; set; }
        public int PortafolioResponsableId { get; set; }
        public string BuzonSalida { get; set; }
        public string ConCopia { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public int HoraEnvio { get; set; }
        public string Asunto { get; set; }
        public string Cuerpo { get; set; }
        public bool FlagEnvio { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<bool> FlagNotificacionTTLJdE { get; set; }
    
        public virtual PortafolioResponsables PortafolioResponsables { get; set; }
    }
}
