//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeticionBigFix
    {
        public int PeticionId { get; set; }
        public string GeneradoPor { get; set; }
        public System.DateTime FechaPeticion { get; set; }
        public string Servidor { get; set; }
        public string Ruta { get; set; }
        public string Email { get; set; }
        public bool FlagProcesado { get; set; }
        public string IdBigFix { get; set; }
    }
}
