//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelacionDetalle
    {
        public long RelacionDetalleId { get; set; }
        public long RelacionId { get; set; }
        public Nullable<int> TecnologiaId { get; set; }
        public int RelevanciaId { get; set; }
        public bool FlagActivo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string ModificadoPor { get; set; }
        public string CodigoAPTVinculo { get; set; }
        public string DetalleVinculo { get; set; }
        public string Componente { get; set; }
    
        public virtual Relevancia Relevancia { get; set; }
        public virtual Relacion Relacion { get; set; }
        public virtual Tecnologia Tecnologia { get; set; }
    }
}
