//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolesProducto
    {
        public int RolesProductoId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public string Rol { get; set; }
        public string GrupoRed { get; set; }
        public Nullable<bool> FlagActivo { get; set; }
        public Nullable<bool> FlagEliminado { get; set; }
        public string Descripcion { get; set; }
        public string RolSeguridad { get; set; }
    }
}
