//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servidor
    {
        public string IdServidor { get; set; }
        public string ShortDescription { get; set; }
        public string SerialNumber { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public string Item { get; set; }
        public string Name { get; set; }
        public Nullable<int> TotalPhysicalMemory { get; set; }
        public string Description { get; set; }
        public string Model { get; set; }
        public string ManufacturerName { get; set; }
        public string Domain { get; set; }
        public string HostName { get; set; }
        public string CapabilityList { get; set; }
        public string NameFormat { get; set; }
        public string A_Ambiente { get; set; }
        public string A_Estado { get; set; }
        public string A_Funcion { get; set; }
        public string Rol_Servidor { get; set; }
        public string Company { get; set; }
        public bool Activo { get; set; }
        public string A_Ubicacion { get; set; }
        public Nullable<bool> Temporal { get; set; }
        public Nullable<int> Obsolescente { get; set; }
        public string Criticidad { get; set; }
        public Nullable<bool> ExcluirCalculo { get; set; }
        public string Fuente_ResourceGroupManual { get; set; }
        public string SistemaOperativoManual { get; set; }
    }
}
