//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudArchivos
    {
        public int IdSolicitudArchivos { get; set; }
        public Nullable<int> IdSolicitud { get; set; }
        public byte[] ConformidadGST { get; set; }
        public byte[] TicketEliminacion { get; set; }
        public byte[] Ratificacion { get; set; }
        public string NombreConformidadGST { get; set; }
        public string NombreTicketEliminacion { get; set; }
        public string NombreRatificacion { get; set; }
    }
}
