//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int SolicitudAplicacionId { get; set; }
        public int TipoSolicitud { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int AplicacionId { get; set; }
        public int EstadoSolicitud { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public string Observaciones { get; set; }
        public Nullable<bool> FlagAprobacion { get; set; }
        public string EstadoAnterior { get; set; }
        public string MatriculaUsuario { get; set; }
        public string NombreUsuarioModificacion { get; set; }
        public string NombreUsuarioAprobacion { get; set; }
        public string NombreUsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public Nullable<bool> VisiblePortafolio { get; set; }
        public Nullable<int> FlowAppId { get; set; }
        public string ObservacionesAprobacion { get; set; }
        public string EmailSolicitante { get; set; }
        public string ObservacionesRechazo { get; set; }
        public Nullable<bool> FlagRequiereConformidad { get; set; }
        public string TicketEliminacion { get; set; }
        public string ExpertoNombre { get; set; }
        public string ExpertoMatricula { get; set; }
        public string ExpertoCorreo { get; set; }
        public Nullable<int> TipoEliminacion { get; set; }
        public string NombreSolicitante { get; set; }
        public Nullable<System.DateTime> FechaRechazo { get; set; }
        public string NombreRechazo { get; set; }
    }
}
