//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudAplicacion
    {
        public string CodigoAPT { get; set; }
        public string Nombre { get; set; }
        public string TipoActivoInformacion { get; set; }
        public string GerenciaCentral { get; set; }
        public string Division { get; set; }
        public string Area { get; set; }
        public string Unidad { get; set; }
        public string DescripcionAplicacion { get; set; }
        public Nullable<System.DateTime> FechaCreacionProcedencia { get; set; }
        public string AreaBIAN { get; set; }
        public string DominioBIAN { get; set; }
        public string JefaturaATI { get; set; }
        public string TribeTechnicalLead { get; set; }
        public string JefeEquipo_ExpertoAplicacionUserIT_ProductOwner { get; set; }
        public string NombreEquipo_Squad { get; set; }
        public string GestionadoPor { get; set; }
        public string Owner_LiderUsuario_ProductOwner { get; set; }
        public string Gestor_UsuarioAutorizador_ProductOwner { get; set; }
        public string EntidadResponsable { get; set; }
        public Nullable<int> CriticidadId { get; set; }
        public string CategoriaTecnologica { get; set; }
        public Nullable<int> RoadMapId { get; set; }
        public Nullable<System.DateTime> FechaRegistroProcedencia { get; set; }
        public string Matricula { get; set; }
        public Nullable<int> Obsolescente { get; set; }
        public bool FlagActivo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<bool> FlagRelacionar { get; set; }
        public string Experto_Especialista { get; set; }
        public Nullable<int> Mes { get; set; }
        public Nullable<int> Anio { get; set; }
        public string EstadoAplicacion { get; set; }
        public string BrokerSistemas { get; set; }
        public Nullable<bool> FlagCargaManual { get; set; }
        public Nullable<bool> FlagAprobado { get; set; }
        public string ClasificacionTecnica { get; set; }
        public string SubclasificacionTecnica { get; set; }
        public string RelacionActualizadoPor { get; set; }
        public string ArquitectoTI { get; set; }
        public string GestorUserIT { get; set; }
        public Nullable<System.DateTime> FechaCreacionAplicacion { get; set; }
        public int AplicacionId { get; set; }
        public Nullable<bool> FlagAprobacionSol { get; set; }
    }
}
