//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudCampos
    {
        public int SolicitudCamposId { get; set; }
        public string ApplicationId { get; set; }
        public Nullable<int> ColumnaId { get; set; }
        public string ValorAnterior { get; set; }
        public string NuevoValor { get; set; }
        public Nullable<bool> EstadoPendiente { get; set; }
        public Nullable<int> SolicitudId { get; set; }
    }
}
