//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudCampoModificado
    {
        public int SolicitudCampoModificadoId { get; set; }
        public int SolicitudAplicacionId { get; set; }
        public int AtributoAplicacionId { get; set; }
        public string ValorNuevo { get; set; }
        public bool FlagActivo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<int> TablaProcedenciaId { get; set; }
        public Nullable<int> ModuloId { get; set; }
    }
}
