//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamSquad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamSquad()
        {
            this.TribeLeader = new HashSet<TribeLeader>();
        }
    
        public int EquipoId { get; set; }
        public int GestionadoPorId { get; set; }
        public string Nombre { get; set; }
        public string Responsable { get; set; }
        public string ResponsableMatricula { get; set; }
        public string ResponsableCorreo { get; set; }
        public string CodigoSIGA { get; set; }
        public bool FlagActivo { get; set; }
        public bool FlagEliminado { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public Nullable<System.DateTime> Fec_Fin_Vigencia { get; set; }
    
        public virtual GestionadoPor GestionadoPor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TribeLeader> TribeLeader { get; set; }
    }
}
