//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TecnologiaNoRegistrada
    {
        public int TecnologiaNoRegistradaId { get; set; }
        public string Aplicacion { get; set; }
        public string Equipo { get; set; }
        public Nullable<int> EquipoId { get; set; }
        public Nullable<int> TipoEquipoId { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public bool FlagAsociado { get; set; }
        public string ClasificacionSugerida { get; set; }
        public Nullable<System.DateTime> FechaEscaneo { get; set; }
        public Nullable<System.DateTime> FechaFinSoporte { get; set; }
        public Nullable<int> Obsoleto { get; set; }
        public Nullable<System.DateTime> FechaFinSoporteExtendido { get; set; }
    }
}
