//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnologia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tecnologia()
        {
            this.ArquetipoTecnologia = new HashSet<ArquetipoTecnologia>();
            this.AutorizadorTecnologia = new HashSet<AutorizadorTecnologia>();
            this.EquipoTecnologia = new HashSet<EquipoTecnologia>();
            this.Excepcion = new HashSet<Excepcion>();
            this.RelacionDetalle = new HashSet<RelacionDetalle>();
            this.TecnologiaVinculada = new HashSet<TecnologiaVinculada>();
            this.TecnologiaVinculada1 = new HashSet<TecnologiaVinculada>();
            this.TecnologiaCicloVida = new HashSet<TecnologiaCicloVida>();
            this.TecnologiaEquivalencia = new HashSet<TecnologiaEquivalencia>();
        }
    
        public int TecnologiaId { get; set; }
        public Nullable<int> TipoTecnologia { get; set; }
        public Nullable<int> FamiliaId { get; set; }
        public int SubdominioId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public int EstadoTecnologia { get; set; }
        public string Versiones { get; set; }
        public Nullable<System.DateTime> FechaLanzamiento { get; set; }
        public Nullable<System.DateTime> FechaFinSoporte { get; set; }
        public Nullable<System.DateTime> FechaAcordada { get; set; }
        public Nullable<System.DateTime> FechaExtendida { get; set; }
        public string ComentariosFechaFin { get; set; }
        public Nullable<int> Existencia { get; set; }
        public Nullable<int> Facilidad { get; set; }
        public Nullable<int> Riesgo { get; set; }
        public Nullable<decimal> Vulnerabilidad { get; set; }
        public string CasoUso { get; set; }
        public string Requisitos { get; set; }
        public string Compatibilidad { get; set; }
        public string Aplica { get; set; }
        public Nullable<int> EliminacionTecObsoleta { get; set; }
        public string Referencias { get; set; }
        public string PlanTransConocimiento { get; set; }
        public string EsqMonitoreo { get; set; }
        public string LineaBaseSeg { get; set; }
        public string EsqPatchManagement { get; set; }
        public string DuenoId { get; set; }
        public string EqAdmContacto { get; set; }
        public string GrupoSoporteRemedy { get; set; }
        public string ConfArqSegId { get; set; }
        public string ConfArqTecId { get; set; }
        public string EncargRenContractual { get; set; }
        public string EsqLicenciamiento { get; set; }
        public string SoporteEmpresarial { get; set; }
        public Nullable<bool> FlagFechaFinSoporte { get; set; }
        public Nullable<System.DateTime> FechaAprobacion { get; set; }
        public string UsuarioAprobacion { get; set; }
        public string Observacion { get; set; }
        public Nullable<bool> FlagAplicacion { get; set; }
        public string CodigoAPT { get; set; }
        public Nullable<int> FuenteId { get; set; }
        public Nullable<bool> FlagSiteEstandar { get; set; }
        public Nullable<int> FechaCalculoTec { get; set; }
        public string Fabricante { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<int> ArquetipoId { get; set; }
        public string ClaveTecnologia { get; set; }
        public string CodigoTecnologiaAsignado { get; set; }
        public string RoadmapOpcional { get; set; }
        public Nullable<bool> FlagConfirmarFamilia { get; set; }
        public Nullable<bool> FlagCambioEstado { get; set; }
        public string UrlConfluence { get; set; }
        public Nullable<int> AutomatizacionImplementadaId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public bool FlagEliminado { get; set; }
        public Nullable<int> AplicacionId { get; set; }
        public Nullable<bool> MostrarSiteEstandaresId { get; set; }
        public Nullable<bool> FlagTieneEquivalencias { get; set; }
        public Nullable<int> MotivoId { get; set; }
        public string CodigoProducto { get; set; }
        public Nullable<int> RevisionSeguridadId { get; set; }
        public string RevisionSeguridadDescripcion { get; set; }
        public Nullable<System.DateTime> FechaCalculo { get; set; }
        public string CompatibilidadSOId { get; set; }
        public string CompatibilidadCloudId { get; set; }
        public string EquipoAprovisionamiento { get; set; }
        public byte[] CasoUsoArchivo { get; set; }
        public string SustentoMotivo { get; set; }
        public string SustentoUrl { get; set; }
        public string TipoFechaInterna { get; set; }
        public Nullable<int> UrlConfluenceId { get; set; }
        public Nullable<bool> FlagAprobado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArquetipoTecnologia> ArquetipoTecnologia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutorizadorTecnologia> AutorizadorTecnologia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquipoTecnologia> EquipoTecnologia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Excepcion> Excepcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelacionDetalle> RelacionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TecnologiaVinculada> TecnologiaVinculada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TecnologiaVinculada> TecnologiaVinculada1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TecnologiaCicloVida> TecnologiaCicloVida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TecnologiaEquivalencia> TecnologiaEquivalencia { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
