//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoNotificacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoNotificacion()
        {
            this.Notificacion = new HashSet<Notificacion>();
        }
    
        public int TipoNotificacionId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string BuzonSalida { get; set; }
        public string Para { get; set; }
        public string ConCopia { get; set; }
        public string Asunto { get; set; }
        public string Cuerpo { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<int> HoraEnvio { get; set; }
        public Nullable<System.DateTime> FechaUltimoEnvio { get; set; }
        public string CuerpoAlternativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificacion> Notificacion { get; set; }
    }
}
