//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoNotificacionApp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TipoNotificacionApp()
        {
            this.NotificacionApp = new HashSet<NotificacionApp>();
        }
    
        public int TipoNotificacionId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string BuzonSalida { get; set; }
        public string Para { get; set; }
        public string ConCopia { get; set; }
        public string Asunto { get; set; }
        public string Cuerpo { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<int> HoraEnvio { get; set; }
        public Nullable<System.DateTime> FechaUltimoEnvio { get; set; }
        public string CuerpoAlternativo { get; set; }
        public Nullable<bool> Solicitante { get; set; }
        public Nullable<bool> ArquitectoNegocio { get; set; }
        public Nullable<bool> ATI { get; set; }
        public Nullable<bool> LiderUsuario { get; set; }
        public Nullable<bool> TL_TTL { get; set; }
        public Nullable<bool> DevSec { get; set; }
        public Nullable<bool> JefeEquipo { get; set; }
        public Nullable<bool> UsuarioAutorizador { get; set; }
        public Nullable<bool> Brokerr { get; set; }
        public Nullable<bool> GobiernoIT { get; set; }
        public Nullable<bool> AIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificacionApp> NotificacionApp { get; set; }
    }
}
