//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoCicloVida
    {
        public int TipoCicloVidaId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int NroPeriodosEstadoAmbar { get; set; }
        public bool FlagDefault { get; set; }
        public bool FlagActivo { get; set; }
        public bool FlagEliminado { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string ModificadoPor { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    }
}
