//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TribeLeader
    {
        public int TribeLeaderId { get; set; }
        public int EquipoId { get; set; }
        public string Responsable { get; set; }
        public string ResponsableMatricula { get; set; }
        public string ResponsableCorreo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public bool Activo { get; set; }
    
        public virtual TeamSquad TeamSquad { get; set; }
    }
}
