//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCP.CVT.Services.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlAplicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UrlAplicacion()
        {
            this.UrlAplicacionEquipo = new HashSet<UrlAplicacionEquipo>();
        }
    
        public int UrlAplicacionId { get; set; }
        public string Url { get; set; }
        public string CodigoAPT { get; set; }
        public Nullable<int> EquipoId { get; set; }
        public string NombreEquipo { get; set; }
        public int UrlFuenteId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaUltimaActualizacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<bool> FlagEditarAplicacion { get; set; }
        public Nullable<bool> FlagActivo { get; set; }
        public string Comentario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrlAplicacionEquipo> UrlAplicacionEquipo { get; set; }
        public virtual UrlFuente UrlFuente { get; set; }
    }
}
